# Generated by Django 6.0.1 on 2026-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nimra Farooq', max_length=100)),
                ('job_title', models.CharField(default='Computer Science Student', max_length=100)),
                ('description', models.TextField(default='I am a passionate developer currently studying BS Computer Science...')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
    ]
